# Generated by Django 5.1.5 on 2025-01-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_stripe_price_id_product_stripe_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=52, null=True),
        ),
    ]
