# Generated by Django 5.1.5 on 2025-01-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_cart_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.FloatField(blank=True, default=10.1, null=True),
        ),
    ]
