# Generated by Django 5.1.5 on 2025-01-24 14:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_cart_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
